version: "3"
services:
  board:
    build: .
    restart: on-failure #컨테이너 재실행
    container_name: board_1
    depends_on: #database service가 실행된 이후에 실행
      - mariadb_1
    ports:
      - 80:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb_1:3306/wanted__prod?useUnicode=true
      SPRING_DATASOURCE_USERNAME: lldjlocal
      SPRING_DATASOURCE_PASSWORD: 1234


