version: "3"
services:
  database:
    image: mysql
    container_name: mysql_1
    restart: unless-stopped
    environment: # 환경 설정
      - MARIADB_ROOT_PASSWORD=lldj123414
      - TZ=Asia/Seoul
    ports: #port 지정
      - 3306:3306
    volumes: #볼륨 지정
      - /docker_projects/mariadb_1/conf.d:/etc/mysql/conf.d
      - /docker_projects/mariadb_1/mysql:/var/lib/mysql
      - /docker_projects/mariadb_1/run/mysqld:/run/mysqld/
    networks: #사용할 네트워크 지정
      - board_network
    command: >
      sh -c "mysql -h localhost -u root -p'\$MYSQL_ROOT_PASSWORD' -e '
      CREATE DATABASE IF NOT EXISTS wanted__prod;
      CREATE DATABASE IF NOT EXISTS nginx;
      GRANT ALL PRIVILEGES ON *.* TO \"lldj\"@\"%\" IDENTIFIED BY \"lldj123414\";
      GRANT ALL PRIVILEGES ON *.* TO \"lldjlocal\"@\"127.0.0.1\" IDENTIFIED BY \"1234\";
      GRANT ALL PRIVILEGES ON *.* TO \"lldjlocal\"@\"172.17.%.%\" IDENTIFIED BY \"1234\";
      '"

  webapp:
    build: #image를 DockerFile 기반으로 사용한다
      context: .
      dockerfile: Dockerfile    #기존에 설정해둔 DockerFile을 지정히여 build 된 jar 파일을 container에 올린다.
    restart: always        #컨테이너 재실행
    depends_on: #database service가 실행된 이후에 실행
      - database
    ports:
      - 8080:8080
    container_name: board_1
    networks:
      - board_network

networks:	#네트워크 설정
  board_network:
