version: "3"
services:
  database:
    image: mariadb:latest
    container_name: mariadb_1
    restart: unless-stopped
    environment: # 환경 설정
      - MARIADB_DATABASE=wanted__prod
      - MARIADB_ROOT_PASSWORD=lldj123414
      - TZ=Asia/Seoul
    ports: #port 지정
      - 3306:3306
    volumes: #볼륨 지정
      - ./mysql-init.d:/docker-entrypoint-initdb.d
    networks: #사용할 네트워크 지정
      - boardapi_network
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'

  webapp:
    build: .
    restart: always        #컨테이너 재실행
    depends_on: #database service가 실행된 이후에 실행
      - database
    ports:
      - 8080:8080
    container_name: boardapi_1
    networks:
      - boardapi_network
networks:
  boardapi_network:
