version: "3"
services:
  mariadb_1:
    image: mariadb:latest
    container_name: mariadb_1
    environment: # 환경 설정
      - MARIADB_DATABASE=wanted__prod
      - MARIADB_ROOT_HOST=%
      - MARIADB_ROOT_PASSWORD=lldj123414
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports: #port 지정
      - 3306:3306
    volumes:
      - ~/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql
      - ~/docker/mariadb/var/log/maria:/var/log/maria
  board:
    build: .
    restart: on-failure #컨테이너 재실행
    container_name: board_1
    depends_on: #database service가 실행된 이후에 실행
      - mariadb_1
    ports:
      - 80:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb_1:3306/wanted__prod?useUnicode=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234


