spring:
  datasource:
    driver-class-name: ${test.db.driver-class-name}
    url: ${test.db.url}
    username: ${test.db.username}
    password: ${test.db.password:NONE}
  jpa:
    hibernate:
      ddl-auto: create
